# action.yml
name: 'AsciiDoctor'
description: 'AsciiDoc Build action'
inputs:
    shellcommand:  # id of input
        description: 'AsciiDoc Build command'
        required: true
        default: 'asciidoctor index.adoc'
outputs:
    time: # id of output
        description: 'Build Finish Time'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.shellcommand }}
    
    